


create
(:Characteristics_details{rtpl_id:"1267",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"1267",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"1267",name:"cart",definition:"cart",price:"13000",price_period:"month",restart_id:"5016"})
;
create
(:Characteristics_details{rtpl_id:"3011",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"3011",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3011",name:"cart",definition:"cart",price:"45000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"17",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/special_offers2/smartphone_by_subscription",name_ru:"https://ucell.uz/ru/subscribers/services2/special_offers2/smartphone_by_subscription",name_en:"https://ucell.uz/en/subscribers/services2/special_offers2/smartphone_by_subscription"}),
(:Characteristics_details{rtpl_id:"17",name:"slogan",definition:"slogan",name_uz:"«Obuna bo‘yicha smartfon» – muddatli to‘lovdan arzonroq!",name_ru:"«Смартфон по подписке» - дешевле, чем рассрочка!",name_en:"“Smartphone by subscription” is more affordable than by installments!"}),
(:Characteristics_details{rtpl_id:"17",name:"cart",definition:"cart",price:"35000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"290",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line"}),
(:Characteristics_details{rtpl_id:"290",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"290",name:"cart",definition:"cart",price:"82000",price_period:"month",restart_id:"5039"})
;
create
(:Characteristics_details{rtpl_id:"320",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"320",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"320",name:"cart",definition:"cart",price:"45000",price_period:"month",restart_id:"5048"})
;
create
(:Characteristics_details{rtpl_id:"9",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/special_offers2/smartphone_by_subscription",name_ru:"https://ucell.uz/ru/subscribers/services2/special_offers2/smartphone_by_subscription",name_en:"https://ucell.uz/en/subscribers/services2/special_offers2/smartphone_by_subscription"}),
(:Characteristics_details{rtpl_id:"9",name:"slogan",definition:"slogan",name_uz:"«Obuna bo‘yicha smartfon» – muddatli to‘lovdan arzonroq!",name_ru:"«Смартфон по подписке» - дешевле, чем рассрочка!",name_en:"“Smartphone by subscription” is more affordable than by installments!"}),
(:Characteristics_details{rtpl_id:"9",name:"cart",definition:"cart",price:"50000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"269",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"269",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"269",name:"cart",definition:"cart",price:"20000",price_period:"month",restart_id:"5001"})
;
create
(:Characteristics_details{rtpl_id:"343",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/tariff_line_Online_Webkassa",name_ru:"https://ucell.uz/ru/subscribers/tariffs/tariff_line_Online_Webkassa",name_en:"https://ucell.uz/en/subscribers/tariffs/tariff_line_Online_Webkassa"}),
(:Characteristics_details{rtpl_id:"343",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"343",name:"cart",definition:"cart",price:"13000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"112",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/m2m_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/m2m_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/m2m_tariff_line"}),
(:Characteristics_details{rtpl_id:"112",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"112",name:"cart",definition:"cart",price:"210.5",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"138",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"138",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"138",name:"cart",definition:"cart",price:"50",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3246",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx",name_ru:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx",name_en:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx"}),
(:Characteristics_details{rtpl_id:"3246",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3246",name:"cart",definition:"cart",price:"300000",price_period:"month",restart_id:"5544"})
;
create
(:Characteristics_details{rtpl_id:"3229",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3229",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3229",name:"cart",definition:"cart",price:"30000",price_period:"month",restart_id:"5399"})
;
create
(:Characteristics_details{rtpl_id:"3241",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/Foydali",name_ru:"https://ucell.uz/ru/subscribers/tariffs/Foydali",name_en:"https://ucell.uz/en/subscribers/tariffs/Foydali"}),
(:Characteristics_details{rtpl_id:"3241",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3241",name:"cart",definition:"cart",price:"23000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"50",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2B/Maqsad_offer_uz.pdf",name_ru:"https://ucell.uz/media/files/docs/B2B/Maqsad_offer_ru.pdf",name_en:"https://ucell.uz/media/files/docs/B2B/Maqsad_offer_en.pdf"}),
(:Characteristics_details{rtpl_id:"50",name:"slogan",definition:"slogan",name_uz:"Yakka tartibdagi tadbirkorlar uchun maxsus tarif",name_ru:"Специальный тариф для частных предпринимателей",name_en:"Tariff plan for individual entrepreneurs"}),
(:Characteristics_details{rtpl_id:"50",name:"cart",definition:"cart",price:"50000",price_period:"month",restart_id:"5250"})
;
create
(:Characteristics_details{rtpl_id:"259",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"259",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"259",name:"cart",definition:"cart",price:"80000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3233",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3233",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3233",name:"cart",definition:"cart",price:"100000",price_period:"month",restart_id:"5403"})
;
create
(:Characteristics_details{rtpl_id:"235",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line"}),
(:Characteristics_details{rtpl_id:"235",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"235",name:"cart",definition:"cart",price:"20000",price_period:"month",restart_id:"5026"})
;
create
(:Characteristics_details{rtpl_id:"211",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line"}),
(:Characteristics_details{rtpl_id:"211",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"211",name:"cart",definition:"cart",price:"100000",price_period:"month",restart_id:"5019"})
;
create
(:Characteristics_details{rtpl_id:"7",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf"}),
(:Characteristics_details{rtpl_id:"7",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"7",name:"cart",definition:"cart",price:"100000",price_period:"month",restart_id:"977"})
;
create
(:Characteristics_details{rtpl_id:"193",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"Dealer A",name_en:""}),
(:Characteristics_details{rtpl_id:"193",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"193",name:"cart",definition:"cart",price:"0",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3225",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3225",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3225",name:"cart",definition:"cart",price:"15000",price_period:"month",restart_id:"5397"})
;
create
(:Characteristics_details{rtpl_id:"183",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tariff_home",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tariff_home",name_en:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tariff_home"}),
(:Characteristics_details{rtpl_id:"183",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"183",name:"cart",definition:"cart",price:"170",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3228",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3228",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3228",name:"cart",definition:"cart",price:"20000",price_period:"month",restart_id:"5395"})
;
create
(:Characteristics_details{rtpl_id:"296",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line"}),
(:Characteristics_details{rtpl_id:"296",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"296",name:"cart",definition:"cart",price:"19000",price_period:"month",restart_id:"5041"})
;
create
(:Characteristics_details{rtpl_id:"333",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line"}),
(:Characteristics_details{rtpl_id:"333",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"333",name:"cart",definition:"cart",price:"30000",price_period:"month",restart_id:"5263"})
;
create
(:Characteristics_details{rtpl_id:"288",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line"}),
(:Characteristics_details{rtpl_id:"288",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"288",name:"cart",definition:"cart",price:"37000",price_period:"month",restart_id:"5037"})
;
create
(:Characteristics_details{rtpl_id:"257",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"257",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"257",name:"cart",definition:"cart",price:"35000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"233",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"233",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"233",name:"cart",definition:"cart",price:"6057.81",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3227",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3227",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3227",name:"cart",definition:"cart",price:"60000",price_period:"month",restart_id:"5398"})
;
create
(:Characteristics_details{rtpl_id:"297",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line"}),
(:Characteristics_details{rtpl_id:"297",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"297",name:"cart",definition:"cart",price:"23000",price_period:"month",restart_id:"5042"})
;
create
(:Characteristics_details{rtpl_id:"258",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"258",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"258",name:"cart",definition:"cart",price:"55000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"209",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line"}),
(:Characteristics_details{rtpl_id:"209",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"209",name:"cart",definition:"cart",price:"45000",price_period:"month",restart_id:"5017"})
;
create
(:Characteristics_details{rtpl_id:"173",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/more",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/more",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/more"}),
(:Characteristics_details{rtpl_id:"173",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"173",name:"cart",definition:"cart",price:"500",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"201",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"201",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"201",name:"cart",definition:"cart",price:"1000",price_period:"day",restart_id:"5010"})
;
create
(:Characteristics_details{rtpl_id:"571",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/new_foydali",name_ru:"https://ucell.uz/ru/subscribers/tariffs/new_foydali",name_en:"https://ucell.uz/en/subscribers/tariffs/new_foydali"}),
(:Characteristics_details{rtpl_id:"571",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"571",name:"cart",definition:"cart",price:"25000",price_period:"month",restart_id:"49"})
;
create
(:Characteristics_details{rtpl_id:"160",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"160",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"160",name:"cart",definition:"cart",price:"942.31",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"200",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"200",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"200",name:"cart",definition:"cart",price:"650",price_period:"day",restart_id:"5000"})
;
create
(:Characteristics_details{rtpl_id:"260",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"260",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"260",name:"cart",definition:"cart",price:"125000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"157",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"157",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"157",name:"cart",definition:"cart",price:"1728.5",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"250",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"250",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"250",name:"cart",definition:"cart",price:"35000",price_period:"month",restart_id:"5029"})
;
create
(:Characteristics_details{rtpl_id:"253",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"253",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"253",name:"cart",definition:"cart",price:"125000",price_period:"month",restart_id:"5033"})
;
create
(:Characteristics_details{rtpl_id:"3234",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3234",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3234",name:"cart",definition:"cart",price:"150000",price_period:"month",restart_id:"5404"})
;
create
(:Characteristics_details{rtpl_id:"3012",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"3012",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3012",name:"cart",definition:"cart",price:"70000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"222",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"222",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"222",name:"cart",definition:"cart",price:"0",price_period:"",restart_id:""})
;
create
(:Characteristics_details{rtpl_id:"207",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/m2m_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/m2m_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/m2m_tariff_line"}),
(:Characteristics_details{rtpl_id:"207",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"207",name:"cart",definition:"cart",price:"6500",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3224",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3224",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3224",name:"cart",definition:"cart",price:"10000",price_period:"month",restart_id:"5394"})
;
create
(:Characteristics_details{rtpl_id:"230",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/student",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/student",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/student"}),
(:Characteristics_details{rtpl_id:"230",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"230",name:"cart",definition:"cart",price:"10000",price_period:"month",restart_id:"5024"})
;
create
(:Characteristics_details{rtpl_id:"3013",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/services2/services_archive/wished_number",name_ru:"https://ucell.uz/ru/subscribers/services2/services_archive/wished_number",name_en:"https://ucell.uz/en/subscribers/services2/services_archive/wished_number"}),
(:Characteristics_details{rtpl_id:"3013",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3013",name:"cart",definition:"cart",price:"100000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"307",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/prostoy",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/prostoy",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/prostoy"}),
(:Characteristics_details{rtpl_id:"307",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"307",name:"cart",definition:"cart",price:"380",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3232",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3232",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3232",name:"cart",definition:"cart",price:"70000",price_period:"month",restart_id:"5402"})
;
create
(:Characteristics_details{rtpl_id:"298",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/cosmo_tariff_line"}),
(:Characteristics_details{rtpl_id:"298",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"298",name:"cart",definition:"cart",price:"28000",price_period:"month",restart_id:"5043"})
;
create
(:Characteristics_details{rtpl_id:"304",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line"}),
(:Characteristics_details{rtpl_id:"304",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"304",name:"cart",definition:"cart",price:"0",price_period:"day",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"236",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line"}),
(:Characteristics_details{rtpl_id:"236",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"236",name:"cart",definition:"cart",price:"30000",price_period:"month",restart_id:"5027"})
;
create
(:Characteristics_details{rtpl_id:"321",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"321",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"321",name:"cart",definition:"cart",price:"70000",price_period:"month",restart_id:"5373"})
;
create
(:Characteristics_details{rtpl_id:"156",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"156",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"156",name:"cart",definition:"cart",price:"1463.87",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3301",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/Welcome_M",name_ru:"https://ucell.uz/ru/subscribers/tariffs/Welcome_M",name_en:"https://ucell.uz/en/subscribers/tariffs/Welcome_M"}),
(:Characteristics_details{rtpl_id:"3301",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3301",name:"cart",definition:"cart",price:"50000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf "}),
(:Characteristics_details{rtpl_id:"3",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3",name:"cart",definition:"cart",price:"25000",price_period:"month",restart_id:"973"})
;
create
(:Characteristics_details{rtpl_id:"3231",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3231",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3231",name:"cart",definition:"cart",price:"50000",price_period:"month",restart_id:"5401"})
;
create
(:Characteristics_details{rtpl_id:"159",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"159",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"159",name:"cart",definition:"cart",price:"1239.25",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"8",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf ",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf "}),
(:Characteristics_details{rtpl_id:"8",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"8",name:"cart",definition:"cart",price:"150000",price_period:"month",restart_id:"978"})
;
create
(:Characteristics_details{rtpl_id:"5",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf ",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf "}),
(:Characteristics_details{rtpl_id:"5",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"5",name:"cart",definition:"cart",price:"50000",price_period:"month",restart_id:"975"})
;
create
(:Characteristics_details{rtpl_id:"289",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line"}),
(:Characteristics_details{rtpl_id:"289",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"289",name:"cart",definition:"cart",price:"57000",price_period:"month",restart_id:"5038"})
;
create
(:Characteristics_details{rtpl_id:"6",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf ",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf "}),
(:Characteristics_details{rtpl_id:"6",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"6",name:"cart",definition:"cart",price:"70000",price_period:"month",restart_id:"976"})
;
create
(:Characteristics_details{rtpl_id:"341",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/tariff_line_Online_Webkassa",name_ru:"https://ucell.uz/ru/subscribers/tariffs/tariff_line_Online_Webkassa",name_en:"https://ucell.uz/en/subscribers/tariffs/tariff_line_Online_Webkassa"}),
(:Characteristics_details{rtpl_id:"341",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"341",name:"cart",definition:"cart",price:"5000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"206",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/m2m_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/m2m_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/m2m_tariff_line"}),
(:Characteristics_details{rtpl_id:"206",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"206",name:"cart",definition:"cart",price:"30000",price_period:"year",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3247",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx",name_ru:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx",name_en:"https://ucell.uz/media/files/docs/Exclusive/Premium300_Exclusive500.docx"}),
(:Characteristics_details{rtpl_id:"3247",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"3247",name:"cart",definition:"cart",price:"500000",price_period:"month",restart_id:"5545"})
;
create
(:Characteristics_details{rtpl_id:"251",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"251",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"251",name:"cart",definition:"cart",price:"55000",price_period:"month",restart_id:"5030"})
;
create
(:Characteristics_details{rtpl_id:"319",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"319",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"319",name:"cart",definition:"cart",price:"150000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"256",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/marhamat_tariff",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/marhamat_tariff",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/marhamat_tariff"}),
(:Characteristics_details{rtpl_id:"256",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"256",name:"cart",definition:"cart",price:"10000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"3230",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs",name_ru:"https://ucell.uz/ru/subscribers/tariffs",name_en:"https://ucell.uz/en/subscribers/tariffs"}),
(:Characteristics_details{rtpl_id:"3230",name:"slogan",definition:"slogan",name_uz:"Shunchaki. Hamisha. Arzonroq.",name_ru:"Просто. Всегда. Дешевле.",name_en:"Simple. Always. More affordable."}),
(:Characteristics_details{rtpl_id:"3230",name:"cart",definition:"cart",price:"40000",price_period:"month",restart_id:"5400"})
;
create
(:Characteristics_details{rtpl_id:"161",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"161",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"161",name:"cart",definition:"cart",price:"2673.12",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"291",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_plus_tariff_line"}),
(:Characteristics_details{rtpl_id:"291",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"291",name:"cart",definition:"cart",price:"127000",price_period:"month",restart_id:"5040"})
;
create
(:Characteristics_details{rtpl_id:"176",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscrirs/tariffs/thankfully",name_ru:"https://ucell.uz/ru/subscribers/tariffs/thankfully",name_en:"https://ucell.uz/ensubscribers/tariffs/thankfully"}),
(:Characteristics_details{rtpl_id:"176",name:"slogan",definition:"slogan",name_uz:"Imtiyozli tarif rejasi!",name_ru:"Льготный тарифный план!",name_en:"Beneficial tariff plan!"}),
(:Characteristics_details{rtpl_id:"176",name:"cart",definition:"cart",price:"0",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"155",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"155",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"155",name:"cart",definition:"cart",price:"1728.5",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"4",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf ",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf "}),
(:Characteristics_details{rtpl_id:"4",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"4",name:"cart",definition:"cart",price:"35000",price_period:"month",restart_id:"974"})
;
create
(:Characteristics_details{rtpl_id:"210",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/active_tariff_line"}),
(:Characteristics_details{rtpl_id:"210",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"210",name:"cart",definition:"cart",price:"70000",price_period:"month",restart_id:"5018"})
;
create
(:Characteristics_details{rtpl_id:"202",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"202",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"202",name:"cart",definition:"cart",price:"1250",price_period:"day",restart_id:"5002"})
;
create
(:Characteristics_details{rtpl_id:"322",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"322",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"322",name:"cart",definition:"cart",price:"100000",price_period:"month",restart_id:"5374"})
;
create
(:Characteristics_details{rtpl_id:"51005259",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"51005259",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"51005259",name:"cart",definition:"cart",price:"50",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"234",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/tantana_tariff_line"}),
(:Characteristics_details{rtpl_id:"234",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"234",name:"cart",definition:"cart",price:"15000",price_period:"month",restart_id:"5025"})
;
create
(:Characteristics_details{rtpl_id:"342",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/tariff_line_Online_Webkassa",name_ru:"https://ucell.uz/ru/subscribers/tariffs/tariff_line_Online_Webkassa",name_en:"https://ucell.uz/en/subscribers/tariffs/tariff_line_Online_Webkassa"}),
(:Characteristics_details{rtpl_id:"342",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"342",name:"cart",definition:"cart",price:"9000",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"252",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/special_tariff_line"}),
(:Characteristics_details{rtpl_id:"252",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"252",name:"cart",definition:"cart",price:"80000",price_period:"month",restart_id:"5031"})
;
create
(:Characteristics_details{rtpl_id:"3300",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/welcome",name_ru:"https://ucell.uz/ru/subscribers/tariffs/welcome",name_en:"https://ucell.uz/en/subscribers/tariffs/welcome"}),
(:Characteristics_details{rtpl_id:"3300",name:"slogan",definition:"slogan",name_uz:"Sayyohlar uchun maxsus tarif reja",name_ru:"Специальный тарифный план для туристов",name_en:"Special tariff plan for tourists"}),
(:Characteristics_details{rtpl_id:"3300",name:"cart",definition:"cart",price:"500",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"18",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/media/files/docs/B2C/Doimiy_uz_26_09_23.pdf",name_ru:"https://ucell.uz/media/files/docs/B2C/Doimiy_ru_24_10_2023.pdf",name_en:"https://ucell.uz/media/files/docs/B2C/Doimiy_en_26_09_23.pdf"}),
(:Characteristics_details{rtpl_id:"18",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"18",name:"cart",definition:"cart",price:"25000",price_period:"month",restart_id:"980"})
;
create
(:Characteristics_details{rtpl_id:"271",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/mood_tariff_line"}),
(:Characteristics_details{rtpl_id:"271",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"271",name:"cart",definition:"cart",price:"25000",price_period:"month",restart_id:"5012"})
;
create
(:Characteristics_details{rtpl_id:"158",name:"exinfo",definition:"exinfo",name_uz:"",name_ru:"*",name_en:""}),
(:Characteristics_details{rtpl_id:"158",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"158",name:"cart",definition:"cart",price:"1463.87",price_period:"month",restart_id:"0"})
;
create
(:Characteristics_details{rtpl_id:"287",name:"exinfo",definition:"exinfo",name_uz:"https://ucell.uz/uz/subscribers/tariffs/prepaid_tariffs_archive/Special_unlim",name_ru:"https://ucell.uz/ru/subscribers/tariffs/prepaid_tariffs_archive/Special_unlim",name_en:"https://ucell.uz/en/subscribers/tariffs/prepaid_tariffs_archive/Special_unlim"}),
(:Characteristics_details{rtpl_id:"287",name:"slogan",definition:"slogan",name_uz:"",name_ru:"",name_en:""}),
(:Characteristics_details{rtpl_id:"287",name:"cart",definition:"cart",price:"139900",price_period:"month",restart_id:"0"})
;

